### ISSUE TITLE
Switch rendering backend to pixi.js

### ISSUE THREAD

**Issue by mystor** [Queens-Hacks/cyberantelopescript#1]
I've been thinking about how to do the rendering backend, and I really don't think that that is the interesting part of the project, so I'm thinking that we should use a tool like pixi which just handles being fast for us. It'll also be nice to have a display graph without having to write one ourselves :)

I'll work on ripping out our rendering code & replacing it with a pixi-style solution soon(ish). This will probably inject some more imperative non-functionalness into the code (as pixi is a JS lib not a clojurescript lib). That being said, if it's the cost for actually not rendering super-duper slowly, I'm sold.

**Comment by jpittis** [comment]
Let's do it. No big deal to write some wrappers around the rendering code.

**Comment by mystor** [comment]
should be done
