### ISSUE TITLE
Off by one on map rendering. Strange non textured line at top of map.

### ISSUE THREAD

**Issue by jpittis** [Queens-Hacks/cyberantelopescript#7]

**Comment by mystor** [comment]
I'm pretty sure this will be fixed by fixing the issue #4, as it's caused by doing (- world-height y) instead of (- world-height y 1) or something like that... Anyways, once the world uses a standardized top-left-is-0-0 coordinate scheme everywhere, I think it will be trivial to fix.

**Comment by jpittis** [comment]
Fixed with 74a0557
